### ISSUE TITLE
Icons starts to blink when trying to open a minimized window

### ISSUE THREAD

**Issue by haoyet** [ubuntu-mate/mate-dock-applet#176]
The behavior or this bug is identical as #60 however I am using Marco and not compiz,

If I change Action when apps need attention settings in the misc tab to show badge instead, then the icon will show the exclamation mark instead of blinking, but the window still doesn't open.

**Comment by tari01** [comment]
Confirmed for v0.88 on Manjaro with MATE 1.22.0. The bug is seemingly without pattern - on some logins the applet will raise minimised windows, on some logins it won't. The behaviour persists during the entire session and may (or may not) change after you log in again. It affects all minimised applications without exception.

**Comment by robint99** [comment]
Seems to happen only on some distros, but  I managed to reproduce it on Antergos and have just committed a fix.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/mate-dock-applet/commit/dcb98fe55f2d90665a2699485cb3d436811105bd
